version: "3.9"

services:
  database: 
    image: postgres
    container_name: nest-api
    restart: always
    ports: 
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=postgres
    volumes:
      - pgdata:/data/postgres

  
  # redis:
  #   image: redis:alpine
  #   ports: 
  #     - 6379:6379



  db:
    build: .
    container_name: rentx
    restart: always
    ports: 
      - 3333:3333
      - 9229:9229
    volumes: 
      - .:/usr/db
    links: 
      - database
    depends_on:
      - database



volumes:
  pgdata:
    driver: local